[log]
logtostderr = true
level = "info"
logdir = "./"

[[tunnel]]
listen = "127.0.0.1:48100"
pac=[{host = ".*", channel = "rmux"}]

[[channel]]
# name of current channel
name = "rmux"
# host & port of server
url = "127.0.0.1:48101"
ping_interval_sec = 10
conns_per_host = 1
max_alive_mins = 40
# cipher to communicate with server
cipher = {key="letmeseethisisapassword", method = "aes128gcm"}


# [[channel]]
# name = "ws"
# url = "wss://testapp.herokuapp.com:443"
# ping_interval_sec = 10
# conns_per_host = 5
# max_alive_mins = 70
# cipher = {key="abcdefg", method = "chacha20poly1305"}
# work_time_frame=[7,22]  #only work between 7am to 22pm
# sni= "www.herokuapp.com"
# sni_proxy="10.10.10.10"
