[log]
logtostderr = true
level = "info"
logdir = "./"


[[tunnel]]
# listen address of tunnel server
listen = "rmux://0.0.0.0:48101"
# pac rule to relay traffic, 'direct' is special channel which relay direct to remote target server
pac=[{host = ".*", channel = "direct"}]
cipher = {key="${RMUX_CIPHER_KEY}", method = "aes128gcm"}

[[tunnel]]
# listen address of tunnel server
listen = "ws://0.0.0.0:48102"
# pac rule to relay traffic, 'direct' is special channel which relay direct to remote target server
pac=[{host = ".*", channel = "direct"}]
cipher = {key="${WS_CIPHER_KEY}", method = "aes128gcm"}
